### PR TITLE
bump(virtual/pkgconfig): sync with upstream

### PR DESCRIPTION
**Pull request by marineam**
Required by newer net-libs/libtirpc-0.2.5 ebuild

Packages updated:
  dev-util/pkgconfig
  virtual/pkgconfig

### CODE REVIEW

**Comment by mischief** [comment]
my bad. is there a way i can check version requirements so this wont happen in the future?

**Comment by marineam** [comment]
Well, in my case emerge usually complains about not being able to build something. In the case of `./build_packages` in some cases it may simply skip over the issue and not upgrade libtirpc so it can be easy to miss. calling `emerge-amd64-usr libtirpc` would fail loudly though.

**Comment by crawford** [comment]
LGTM

**Pull request merged**
