### PR TITLE
bump(app-editors/vim): sync with upstream

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
This should bump vim-core, also most of the vim build is in vim.eclass, are there any associated changes there?

**Comment by mischief** [comment]
@marineam i'm unable to track down vim.eclass, any pointers?

**Comment by mischief** [comment]
@marineam added vim-core sync to this pr.

**Comment by mischief** [comment]
7.4.769 seems to build and run fine in my sdk without any further commits.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
