### PR TITLE
bump(sys-process/lsof): sync with upstream

### PR DESCRIPTION
**Pull request by glevand**
lsof-4.85 was removed from the upstream server.  Fixes build errors like these:
```No such file ‘lsof_4.85.tar.bz2’```

### CODE REVIEW

**Comment by crawford** [comment]
LGTM

**Comment by marineam** [comment]
Weird, in addition to gentoo's mirror we maintain our own mirror of source tarballs. I'll have to check what happened.

**Comment by glevand** [comment]
@marineam I hit that error with the arm64 build, it seems amd64 was using lsof-4.87-r1, so maybe only that one was on your mirror?

**Comment by marineam** [comment]
In theory all versions in our tree are mirrored, we use the same process as Gentoo does but I never watch for files that fail to mirror so it could easily be missed. In any case, this PR LGTM, the mirroring bug is independent. :)

**Pull request merged**
