### PR TITLE
Update packages needed by SELinux

### PR DESCRIPTION
**Pull request by glevand**
Update/import some packages in preparation for updating the SELinux packages.

### CODE REVIEW

**Comment by glevand** [comment]
Rebased to latest.

**Comment by glevand** [comment]
Rebased to latest.

**Comment by dm0-** [comment]
Nevermind about swig; I see it's synced in the second overlay PR.

**Comment by ajeddeloh** [comment]
I built this and the overlay PR locally, passed kola on qemu. I'm gunna run it through a full jenkins run since it updates catalyst.

**Comment by ajeddeloh** [comment]
Just merged: https://github.com/coreos/scripts/blob/master/check_out_of_date.py which will give you what uses each version as part of the json output. You'll have to do some jq wrangling, but it should give you what you want.

**Comment by glevand** [comment]
Added metadata update patch.  Also added a version sync patch to https://github.com/coreos/coreos-overlay/pull/3100 for dev-perl/libintl-perl, dev-perl/Text-Unidecode, and sys-apps/sandbox.

**Pull request merged**
