### PR TITLE
bump(dev-lang/rust): sync with upstream

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by dm0-** [comment]
Is this complete?  Does it not need `rust-eselect`?  It doesn't look like any version is accepted for any architecture for either package.  Version 1.15.1 seems to want to use the system's LLVM by default, which we don't have.

**Comment by crawford** [comment]
Hmm, my SDK must have these installed. Let me start from a clean one and follow up.

**Comment by dm0-** [comment]
Which versions of `rust` and `cargo` are you installing so I can test it?  None of them are marked stable for any architecture.  Also note that `eselect-rust` is only stable for amd64, not arm64.

**Comment by crawford** [comment]
rust-1.19.0 and cargo-0.20.0

I haven't taken a look at ARM yet. I suspect I will need another use flag for LLVM multiarch support.

**Comment by lucab** [comment]
@crawford I'm surprised you have to touch libuv1 here, nothing in the Rust world should be depending on it since at least 1.0.

**Comment by dm0-** [comment]
It is a dependency of `cmake`.

**Pull request merged**
