### PR TITLE
bump(dev-libs/openssl): sync with upstream

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by mischief** [comment]
resolves coreos/coreos-overlay#1156

**Comment by crawford** [comment]
LGTM

**Comment by lamielle** [comment]
Great!  Any estimate on when a build with this PR will land in the Alpha channel?

**Comment by mischief** [comment]
openssl-1.0.1l is now in alpha (633.1.0)

**Comment by lamielle** [comment]
Ok, two questions:
1) Is there a way to get the included openssl version updated in the release notes for this release (https://coreos.com/releases/) similarly to how it was noted previously?
2) 1.0.1m is the update I'm waiting on for a set of security updates.  1.0.1l doesn't appear to have them (per the OpenSSL release notes).  Based on the diff there are references to 1.0.1m and 1.0.1l.  Short of spinning up an instance of 633.1.0, is there a way to check for the version?

**Comment by crawford** [comment]
@lamielle That is my fault. I'm fixing the release notes now.

**Comment by lamielle** [comment]
No problem at all @crawford!  Just trying to determine if 633.1.0 has 1.0.1m (or a patched 1.0.1l) that addresses the recent security issues.  Thanks for the responses.

**Comment by mischief** [comment]
afaict, based on https://security.gentoo.org/glsa/201503-11 https://security.gentoo.org/glsa/201503-11 and https://www.openssl.org/news/openssl-1.0.1-notes.html, the problems that openssl addressed in 1.0.1m have been backported to 1.0.1l-r1.

**Comment by lamielle** [comment]
Thanks for those links.  You're right, this patched version does have those fixes.  Thanks @mischief!  I'll check out 633.1.0 today!

**Pull request merged**
