### PR TITLE
portage-stable: Updates for arm64

### PR DESCRIPTION
**Pull request by glevand**
Sync another 26 packages with upstream to get arm64 keywords, etc.

### CODE REVIEW

**Comment by marineam** [comment]
I've removed pygobject and dbus-python from the tree since they are not actually needed by anything.

**Comment by glevand** [comment]
@marineam It seems dbus-python is still there.  I saw you removed pygobject and pyudev.  Were you working on removing dbus-python?

**Comment by marineam** [comment]
I didn't bother deleting it since it wasn't causing the issue I was hitting but it can be dropped, it shouldn't be getting built into the image now. If you want to merge as-is that's fine, it can be removed later.

LGTM

**Comment by glevand** [comment]
I'll remove the dbus-python patch from this series and look into removing the package.

**Pull request merged**
