### PR TITLE
bump(net-libs/libmicrohttpd): sync with upstream

### PR DESCRIPTION
**Pull request by mischief**
i think we need to sync the arm64 stable keywords in coreos-overlay too.

### CODE REVIEW

**Comment by marineam** [comment]
Is there a PR for the overlay keywords yet?

**Comment by mischief** [comment]
no. stand by.

**Comment by mischief** [comment]
@marineam https://github.com/coreos/coreos-overlay/pull/1585

**Comment by marineam** [comment]
LGTM

**Pull request merged**
