### PR TITLE
sys-cluster/ipvsadm: add package

### PR DESCRIPTION
**Pull request by ajeddeloh**
We ship the kernel bits so we should also ship the userspace bits. Fixes https://github.com/coreos/bugs/issues/1979

### CODE REVIEW

**Comment by ajeddeloh** [comment]
Closing the ebuilds need to be modified and go in the overlay.

**Comment by euank** [comment]
@ajeddeloh accidental reopen?

**Comment by ajeddeloh** [comment]
No, I thought I'd need to modify the ebuild but ended up only needing to change some pkg-config enviroment variables in https://github.com/coreos/coreos-overlay/pull/2707.

**Comment by euank** [comment]
I did a diff on the rootfs before/after adding ipvsadm; should the following ones be in `/usr` instead? Just be not included? Do they matter?

```
/etc/libnl
/etc/libnl/classid
/etc/libnl/pktloc
```

Other than that, the rootfs diff only had fairly expected items (included below for the curious):

```
/usr/lib64/libipvs.so
/usr/lib64/libnl-3.so
/usr/lib64/libnl-3.so.200
/usr/lib64/libnl-3.so.200.22.0
/usr/lib64/libnl-genl-3.so
/usr/lib64/libnl-genl-3.so.200
/usr/lib64/libnl-genl-3.so.200.22.0
/usr/lib64/libnl-idiag-3.so
/usr/lib64/libnl-idiag-3.so.200
/usr/lib64/libnl-idiag-3.so.200.22.0
/usr/lib64/libnl-nf-3.so
/usr/lib64/libnl-nf-3.so.200
/usr/lib64/libnl-nf-3.so.200.22.0
/usr/lib64/libnl-route-3.so
/usr/lib64/libnl-route-3.so.200
/usr/lib64/libnl-route-3.so.200.22.0
/usr/lib64/libnl-xfrm-3.so
/usr/lib64/libnl-xfrm-3.so.200
/usr/lib64/libnl-xfrm-3.so.200.22.0
/usr/sbin/devlink
/usr/sbin/ipvsadm
/usr/sbin/ipvsadm-restore
/usr/sbin/ipvsadm-save
/usr/sbin/tipc
/usr/share/iproute2/bpf_pinning
/var/lib/ipvsadm
/var/lib/ipvsadm/.keep_sys-cluster_ipvsadm-0
```

**Comment by ajeddeloh** [comment]
I did some spluenking and `ipvsadm` only links against `libnl-3` and `libnl-genl-3` and the `/etc` files are only used for the `libnl-route` library (the `libnl` package provides several related libraries). (Confirmed by grepping through source and doubling checking by running `strings` against the .so's). The only downside I can see is if some package in the future does depend on `libnl-route`, it could be broken seemingly without explaination.

**Comment by dm0-** [comment]
If it's not worth the `/etc -> /usr` tmpfiles dance, my preference in that case would be to just drop `/etc/libnl` everywhere.  That way if something does depend on it in the future, we'll be able to notice it without waiting for someone that wiped the root file system or a PXE user to report it.  You can add `/etc/libnl` to `INSTALL_MASK` in the overlay for that.

**Pull request merged**
