### PR TITLE
[WIP] bump(eclass): sync with upstream

### PR DESCRIPTION
**Pull request by iaguis**
Also, regenerate the cache and sync sys-devel/autoconf with upstream because it
was using functions that are banned in EAPI=5 now.

Ref coreos/coreos-overlay#3294

### CODE REVIEW

**Comment by dm0-** [comment]
This is covered by #641, but it's not enough to sync eclasses.  We need an SDK with an updated crossdev built into it, otherwise catalyst build roots will fail.  The plan is to merge #671 to get it included into an alpha release, bump the master manifest branch to that alpha SDK, then merge #641 to update eclasses.  After that, glibc (and other toolchain packages) upgrades should be easier.

**Comment by iaguis** [comment]
Ah, great, thanks for the info!

**Comment by iaguis** [comment]
Feel free to close it if it's not needed :)

**Comment by dm0-** [comment]
Okay, thanks, I'll close this as a duplicate of #641, but your linked overlay PR would still be nice to have.  To guess at a timeline for its dependencies: we might be able to get everything merged by Wednesday.  (Today is the last day for changes in next week's alpha release, so I'll try to get someone to review #671 today to stay on that schedule.)

**Pull request closed without merging**
