### PR TITLE
Revert "bump(app-emulation/qemu): sync with upstream"

### PR DESCRIPTION
**Pull request by crawford**
Reverts coreos/portage-stable#253

### CODE REVIEW

**Comment by crawford** [comment]
This breaks the build.

```
x86_64-pc-linux-gnu-gcc -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/tcg -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/tcg/i386 -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/linux-headers -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/user-build/linux-headers -I. -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0 -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/include -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/target-arm -Itarget-arm -fPIE -DPIE -m64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common  -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits -fstack-protector-all  -I../linux-headers -I.. -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/target-arm -DNEED_CPU_H -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/include -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/linux-user/aarch64 -I/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/linux-user -MMD -MP -MT target-arm/crypto_helper.o -MF target-arm/crypto_helper.d -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -O2 -pipe -mtune=generic  -c -o target-arm/crypto_helper.o /var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/target-arm/crypto_helper.c
make[1]: *** No rule to make target '../qemu-log.c', needed by '../qemu-log.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/portage/app-emulation/qemu-2.3.0-r5/work/qemu-2.3.0/user-build/aarch64-linux-user'
Makefile:173: recipe for target 'subdir-aarch64-linux-user' failed
```

**Comment by marineam** [comment]
Saw a similar build issue on stock Gentoo. LGTM

**Comment by marineam** [comment]
Actually, nm. This appears to be related to my introduction of `CCACHE_BASEDIR=${S}` which I happen to have hacked into my own profile as well. The following works just fine:

```
CCACHE_BASEDIR=/bogus emerge qemu
```

Lets leave this and revert my thing instead.

**Comment by marineam** [comment]
https://github.com/coreos/coreos-overlay/pull/1442

**Pull request closed without merging**
