### PR TITLE
bump(sys-libs/timezone-data): sync with upstream

### PR DESCRIPTION
**Pull request by mischief**
should fix coreos/bugs#353

### CODE REVIEW

**Comment by crawford** [comment]
Can you double check that it is fixed?

**Comment by mischief** [comment]
as soon as the image builds :-)

**Comment by mischief** [comment]
@crawford 

```
core@coreos_production_qemu-668-2-0-2 ~ $ timedatectl 
      Local time: Thu 2015-05-07 16:58:32 UTC
  Universal time: Thu 2015-05-07 16:58:32 UTC
        RTC time: Thu 2015-05-07 16:58:05
       Time zone: UTC (UTC, +0000)
     NTP enabled: no
NTP synchronized: no
 RTC in local TZ: no
      DST active: n/a
core@coreos_production_qemu-668-2-0-2 ~ $ sudo timedatectl set-timezone Europe/Moscow
core@coreos_production_qemu-668-2-0-2 ~ $ timedatectl 
      Local time: Thu 2015-05-07 19:58:36 MSK
  Universal time: Thu 2015-05-07 16:58:36 UTC
        RTC time: Thu 2015-05-07 16:58:10
       Time zone: Europe/Moscow (MSK, +0300)
     NTP enabled: no
NTP synchronized: no
 RTC in local TZ: no
      DST active: n/a
core@coreos_production_qemu-668-2-0-2 ~ $ 
```

**Comment by crawford** [comment]
Great! LGTM

**Pull request merged**
