### PR TITLE
bump(dev-util/cmake): sync with upstream

### PR DESCRIPTION
**Pull request by marineam**
Re-adding cmake, there are still packages in the SDK that depend on it
such as dev-libs/yajl, required by xen-tools.

### CODE REVIEW

**Comment by crawford** [comment]
:( lgtm

**Comment by marineam** [comment]
Depends on https://github.com/coreos/coreos-overlay/pull/1515

**Comment by glevand** [comment]
If we need cmake for arm64 I'll look into to building it with QEMU.

**Comment by marineam** [comment]
@glevand it is only needed in the root of the SDK, not boards. So you are off the hook :)

**Pull request merged**
