### PR TITLE
docker 1.11 deps

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
I think these are the first Go packages for portage-stable so they are using Gentoo's go eclasses instead of ours. Hopefully that's just fine but I want to review those first. On the packages themselves, I'm not sure if we can use the upstream ebuilds since runc/containerd are not mere dependencies of docker, they *are* docker and contain a fair chunk of the code we've had to patch in the past. For example if we still need the overlay/selinux patch that'll probably now be in runc.

**Comment by mischief** [comment]
for docker 1.11.2, the overlay and selinux patches still apply fine to docker.

by dependencies, i simply meant that these are in `$RDEPEND` of app-emulation/docker :smile:

**Comment by marineam** [comment]
Ok, skimmed the gentoo go eclasses, I'm doesn't appear they understand cross compiling. Will need:

    export GOARCH=$(go_get_arch)
    export CGO_ENABLED=1
    export CC=$(tc-getCC)
    export CXX=$(tc-getCXX)

Maybe other tweaks.

**Comment by mischief** [comment]
closing in favor of https://github.com/coreos/coreos-overlay/pull/2022

**Pull request closed without merging**
