### PR TITLE
bump(net-misc/openssh): sync with upstream

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by mischief** [comment]
this sync adds openssh 7.

**Comment by marineam** [comment]
The only thing I worry about is the deprecation of some things, particularly dsa keys. Perhaps we should re-enable them by default to avoid locking people out of their systems.

**Comment by mischief** [comment]
FYI this doesn't actually mark OpenSSH 7 as stable for amd64/arm64.

**Comment by marineam** [comment]
Ok, LGTM then. we can sort out the details in another PR :)

**Comment by mischief** [comment]
this was merged as 9078b954f583b5677cfeb92a95c9aad8f0bd4912, sorry for the fuckup.

**Pull request closed without merging**
