### PR TITLE
prune(net-misc/openssh): moved to coreos-overlay

### PR DESCRIPTION
**Pull request by crawford**
Fixes https://github.com/coreos/bugs/issues/1212.

### CODE REVIEW

**Comment by marineam** [comment]
These belong in coreos-overlay in order to remove the bindist restriction and enable ec

**Comment by crawford** [comment]
Hmm, why is openssh in portage-stable at all?

**Comment by marineam** [comment]
To remove the bindist restriction and enable ec...

**Comment by marineam** [comment]
Oh, sorry, misread. It is in here because no one thought to delete it.

**Comment by marineam** [comment]
So can be pruned :)

**Comment by crawford** [comment]
Pruning

**Pull request merged**
